### ISSUE TITLE
Cannot sign-up to the Slack

### ISSUE THREAD

**Issue by vibl** [ai-sidekick/sidekick#20]
The "Community" link on the doc page (https://sidekick-public.slack.com/) doesn't seem to allow signing up (only signing in).

The "Support" link on the front page (https://join.slack.com/t/sidekick-public/shared_invite/zt-1ra86qug3-~UWNCISLWpNj55Im6C6OaQ) is "no longer active".

**Comment by jasonwcfan** [comment]
Hey @vibl Thanks for pointing that out! We had the wrong link, but it's updated now: https://join.slack.com/t/sidekick-public/shared_invite/zt-1ty1wz6w0-8jkmdvBpM5kj_Fh30EiCcg
