### ISSUE TITLE
No explanation about guardrails implemented

### ISSUE THREAD

**Issue by sundar7D0** [ai-sidekick/sidekick#3]
I came across this article: https://jfan001.medium.com/how-we-cut-the-rate-of-gpt-hallucinations-from-20-to-less-than-2-f3bfcc10e4ec, where you mention about techniques to reduce hallucinations. In the readme.md, you also mention that some guardrails are in place. These are amazing engineering feats to tame GPT3+ but on looking at the code base, I couldn't find the implementation of techniques to reduce hallucinations and the guardrails in place. Please point them!

**Comment by Ayan-Bandyopadhyay** [comment]
Thanks for the feedback @sundar7D0! We're working on a fully self-hostable version of those guardrails right now and we'll add them to the repo very soon.

**Comment by sundar7D0** [comment]
Thanks! Please keep me updated on the guadrails. Also ChatGPT doesn't allow you to have access to output probabilites. Idk what's going to be the workaround in such a scenario!

**Comment by jasonwcfan** [comment]
Hey @sundar7D0 we added the code for the guardrails here: https://github.com/ai-sidekick/sidekick/blob/main/sidekick-server/llm/LLM.py#L63
